import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 该文件在 Node.js 环境下运行，不要在此使用浏览器 API 或 JSX

/**
 * 创建侧边栏可以让你：
 * - 创建一个有序的文档分组
 * - 为该分组中的每个文档渲染一个侧边栏
 * - 提供上一页/下一页导航
 *
 * 侧边栏可以根据文件系统自动生成，也可以在这里显式定义。
 *
 * 你可以创建任意数量的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 会根据 docs 文件夹结构自动生成侧边栏
  noteSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
